---
- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - role: base
      tags: [base, update]

- name: Install Docker on management and k8s nodes
  hosts: management, k8s_cluster
  become: true
  roles:
    - role: docker
      tags: [docker]

- name: Deploy Gitea on management node
  hosts: management
  become: true
  roles:
    - role: gitea
      tags: [gitea]