---
- name: Check if node is already joined to cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join worker node to cluster
  ansible.builtin.command: "{{ hostvars['control-plane']['join_command'] }}"
  when: not kubelet_conf.stat.exists